/**
 * OG image route for marketing posts.
 *
 *   GET /api/og?slug=2026-04-17-short_post
 *
 * Two paths:
 *   1. If public/marketing/<slug>.png exists (a creative generated by
 *      scripts/generate-image.mjs), 307 to the static asset so the CDN
 *      serves it.
 *   2. Otherwise, render a branded card with Satori using the date and
 *      routine parsed from the slug. Always returns 200.
 *
 * Twitter/LinkedIn scrape og:image when someone visits the agent's UTM
 * link, so this endpoint is the single place that decides what social
 * previews look like.
 */

import { ImageResponse } from 'next/og';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { NextRequest } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const WIDTH = 1200;
const HEIGHT = 630;

function parseSlug(slug: string): { date: string; routine: string } {
  const match = slug.match(/^(\d{4}-\d{2}-\d{2})-(.+)$/);
  return {
    date: match?.[1] ?? '',
    routine: (match?.[2] ?? '').replace(/_/g, ' '),
  };
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const slug = (searchParams.get('slug') ?? '').replace(/[^a-z0-9-_]/gi, '');

  if (slug) {
    const creativePath = join(process.cwd(), 'public', 'marketing', `${slug}.png`);
    if (existsSync(creativePath)) {
      const origin = req.headers.get('host')
        ? `https://${req.headers.get('host')}`
        : 'https://jobsearch.quest';
      return Response.redirect(`${origin}/marketing/${slug}.png`, 307);
    }
  }

  const { date, routine } = parseSlug(slug);

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          background: '#FAFAF8',
          padding: '72px',
          fontFamily: 'sans-serif',
        }}
      >
        <div
          style={{
            fontSize: 22,
            color: '#6B7280',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            fontWeight: 500,
          }}
        >
          jobsearch.quest
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: 24,
          }}
        >
          <div
            style={{
              fontSize: 96,
              color: '#111111',
              lineHeight: 1.05,
              fontWeight: 700,
              letterSpacing: '-0.02em',
            }}
          >
            Never Search Alone.
          </div>
          <div
            style={{
              fontSize: 28,
              color: '#374151',
              lineHeight: 1.4,
              maxWidth: 900,
            }}
          >
            An AI-powered Job Search Council.
            Structured, accountable, on your schedule.
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            fontSize: 18,
            color: '#6B7280',
            fontFamily: 'monospace',
          }}
        >
          <span>{date}</span>
          <span
            style={{
              background: '#3B82F6',
              color: '#FFFFFF',
              padding: '6px 14px',
              borderRadius: 4,
              fontSize: 14,
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
            }}
          >
            {routine || 'marketing'}
          </span>
        </div>
      </div>
    ),
    { width: WIDTH, height: HEIGHT },
  );
}
